/*
 * test_gelu.c - Test GELU activation function (Gemma 3)
 *
 * Tests the GELU with tanh approximation used by Gemma 3:
 *   gelu(x) = 0.5 * x * (1 + tanh(sqrt(2/pi) * (x + 0.044715 * x^3)))
 */

#include <u.h>
#include <libc.h>

/* Include test data generated by Python */
#include "gemma3_test_data.h"

/*
 * gelu_tanh - GELU with tanh approximation
 * Matches PyTorch's gelu_pytorch_tanh
 */
static float
gelu_tanh(float x)
{
    float c = 0.7978845608f;  /* sqrt(2/pi) */
    float x3 = x * x * x;
    float inner = c * (x + 0.044715f * x3);
    return 0.5f * x * (1.0f + tanh(inner));
}

void
main(int argc, char *argv[])
{
    int i;
    int passed = 0;
    int failed = 0;
    float result;
    float diff;
    float eps = 1e-5f;

    USED(argc);
    USED(argv);

    print("=== GELU Activation Test ===\n");

    /* Test 1: Basic test values */
    print("\nTest 1: Basic GELU values\n");
    for (i = 0; i < GELU_BASIC_N; i++) {
        result = gelu_tanh(gelu_basic_inputs[i]);
        diff = result - gelu_basic_expected[i];
        if (diff < 0) diff = -diff;

        if (diff < eps) {
            print("  gelu(%.2f) = %.6f (expected %.6f) - PASS\n",
                  gelu_basic_inputs[i], result, gelu_basic_expected[i]);
            passed++;
        } else {
            print("  gelu(%.2f) = %.6f (expected %.6f, diff=%.6f) - FAIL\n",
                  gelu_basic_inputs[i], result, gelu_basic_expected[i], diff);
            failed++;
        }
    }

    /* Test 2: Random values */
    print("\nTest 2: Random GELU values\n");
    for (i = 0; i < GELU_RANDOM_N; i++) {
        result = gelu_tanh(gelu_random_inputs[i]);
        diff = result - gelu_random_expected[i];
        if (diff < 0) diff = -diff;

        if (diff < eps) {
            passed++;
        } else {
            print("  gelu(%.6f) = %.6f (expected %.6f, diff=%.6f) - FAIL\n",
                  gelu_random_inputs[i], result, gelu_random_expected[i], diff);
            failed++;
        }
    }
    if (failed == 0) {
        print("  All %d random values passed\n", GELU_RANDOM_N);
    }

    /* Test 3: Edge cases */
    print("\nTest 3: Edge cases\n");

    /* gelu(0) should be 0 */
    result = gelu_tanh(0.0f);
    if (result == 0.0f) {
        print("  gelu(0) = 0 - PASS\n");
        passed++;
    } else {
        print("  gelu(0) = %.6f (expected 0) - FAIL\n", result);
        failed++;
    }

    /* gelu(x) approaches x for large positive x */
    result = gelu_tanh(10.0f);
    diff = result - 10.0f;
    if (diff < 0) diff = -diff;
    if (diff < 0.01f) {
        print("  gelu(10) ~= 10 (%.6f) - PASS\n", result);
        passed++;
    } else {
        print("  gelu(10) = %.6f (expected ~10) - FAIL\n", result);
        failed++;
    }

    /* gelu(x) approaches 0 for large negative x */
    result = gelu_tanh(-10.0f);
    if (result > -0.01f && result < 0.01f) {
        print("  gelu(-10) ~= 0 (%.6f) - PASS\n", result);
        passed++;
    } else {
        print("  gelu(-10) = %.6f (expected ~0) - FAIL\n", result);
        failed++;
    }

    /* Summary */
    print("\n=== Result ===\n");
    if (failed == 0) {
        print("PASS: All %d GELU tests passed\n", passed);
    } else {
        print("FAIL: %d passed, %d failed\n", passed, failed);
    }

    exits(failed ? "fail" : 0);
}
