</$objtype/mkfile

TARG=run runq export llmfs

all:V: $TARG

run: run.$O
	$LD -o $target $prereq

runq: runq.$O
	$LD -o $target $prereq

export: export.$O
	$LD -o $target $prereq

# llmfs requires lib9p and libthread
llmfs: llmfs.$O
	$LD -o $target $prereq

%.$O: %.c
	$CC $CFLAGS $stem.c

clean:V:
	rm -f *.$O $TARG
